### ISSUE TITLE
BBox isn't preserved during feature() conversion in Client API

### ISSUE THREAD

**Issue by ejabx** [topojson/topojson#112]
It's pretty easy to fix. In `featureOrCollection()` and `feature()` just add the property:

```
bbox: o.bbox
```

**Comment by mbostock** [comment]
There are two bugs here:

* topojson.topology preserves the bbox on features and on geometries that are members of a GeometryCollection, but does not preserve the bbox on a feature’s geometry object. (The GeoJSON spec allows bboxes to be defined on any GeoJSON object.) I’ll change topojson.topology to give the geometry’s bbox priority of the enclosing feature’s bbox, although in practice I only expect one of the two to be defined.

* topojson.feature does not preserve the bbox when converting back to GeoJSON. That issue is covered by topojson/topojson-client#5.
