### ISSUE TITLE
Very large shapefiles seem to crash topojson

### ISSUE THREAD

**Issue by daniel-zillion** [topojson/topojson#248]
The command line topojson utility hangs indefinitely when trying to convert the US Census Tract data (~606 MB) shapefile to a topojson.  Because there is no error message, it's hard to tell what error is occurring, if any.  However, no amount of waiting seems to rectify the issue or produce an error message.  I suspect this behavior would be reproducible with other very large shapefiles, although I don't currently have any available to test.  

This occurs with any options specified (none, -p, -p and -s, etc..).

**Comment by mbostock** [comment]
Running out of memory with large inputs is unfortunately a known issue.

Reducing memory usage requires fairly drastic measures, since the main problem is that the GeoJSON representation (and by inheritance, the TopoJSON representation) is inherently inefficient due to its use of an array of values (`[[x1, y1], [x2, y2], …]`) for each coordinate. This causes thousands or millions of small arrays to be created, introducing substantial overhead and garbage collection penalties.

A better solution is a typed array to hold all coordinates in a single fixed-size buffer (with zip encoding, `[x1, y1, x2, y2]`), or one typed array per dimension (`[x1, x2, …]` and `[y1, y2, …]`). This is not easy, however, since it requires dramatic changes to the internal code.

Until that change happens, I recommend you take a look at [Mapshaper](https://github.com/mbloch/mapshaper), which does a much better job with large shapefiles and can also convert to TopoJSON.

**Comment by daniel-zillion** [comment]
Thanks for the reply. It appears that Mapshaper does indeed support generating TopoJSONs from larger shapefiles than topojson.  However, the utility of that support is not so great because rendering those TopoJSONs still requires client-side conversion back to GeoJSON, which fails because the converted GeoJSON is too large.

**Comment by mbostock** [comment]
Related #80. 2.0 should help with this quite a bit by allowing newline-delimited JSON streams as input (see [shp2json -n](https://github.com/mbostock/shapefile/blob/master/README.md#shp2json_newline_delimited) and [ndjson-cli](https://github.com/mbostock/ndjson-cli)).

But, there remain many potential performance improvements in TopoJSON conversion, most significantly of which would be to use a single typed array for coordinates, or one typed array per dimension, rather than GeoJSON’s inherently inefficient practice of using a separate array for each point. I’m not actively working on that, so I’m closing this issue, but maybe someone else will volunteer.
