### ISSUE TITLE
Simplifying creates polygons with holes that in turn are points

### ISSUE THREAD

**Issue by urbanhop** [topojson/topojson#282]
Simplify simplifies polygons to arcs that have 2 equal points:

```
 [ 26.3929056, 44.2503541 ],
 [ 26.3929056, 44.2503541 ]
```

which actually is a point. A point in turn cannot be a hole of a polygon. Should callers deal with this, or should topojson's simplify already remove arcs, that became "linestring-points"? Such filtering would match TopoJson's optimzation-greedy design, would it?

**Comment by mbostock** [comment]
I’m pretty sure this is the expected behavior. Simplification and quantization guarantee that arcs have at least two points; see [post-quantize.js](https://github.com/mbostock/topojson/blob/master/lib/topojson/post-quantize.js#L41), for example. There’s some code in [filter.js](https://github.com/mbostock/topojson/blob/master/lib/topojson/filter.js) to optionally remove empty rings (and geometries). That’s slightly different than optimizing the generated topology by coalescing degenerate arcs into their neighbors, but the tricky thing there would be to ensure that you preserve the topological relationships between the geometries.

I guess this is a long way of saying that I think the current behavior is reasonable but that it could also be optimized.
