### ISSUE TITLE
Problematic handling of longitudes near +/-180

### ISSUE THREAD

**Issue by mg262** [topojson/topojson#296]
Converting the data in http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip to GeoJSON and then TopoJSON (with `-p 65536`), I find that I am getting arcs like this: 

arc 1632, which starts at (-16.542986, -180.000000) has 4 segments:
(-16.542986, **-180.000000**), (-16.537687, **179.983520**), (-16.529738, 179.983520), (-16.519140, -180.000000), (-16.542986, -180.000000)

Looking back at the source GeoJSON, I found that this came from a polygon 

[179.99921551400016, -16.54145231399994],
[179.99252363400015, -16.543145440999965],
[179.98747806100019, -16.542413018999937],
[179.98454837300008, -16.538262627999913],
[179.98438561300011, -16.530205987999878],
[179.98715254000021, -16.518324476999837],
[179.99915023800023, -16.491329657999955],
[180.0000000000002, -16.489518921999959],
[180.0000000000002, -16.516561427999889],
[180.0000000000002, -16.541274866999913],
[179.99921551400016, -16.54145231399994]

So something is going wrong with the handling of longitudes near 180.0.

Edit: I see that in topology.js, ll. 65-68, you are clamping the bbox to [-180,180].  But are the points in the actual polygons similarly clamped before quantization?

**Comment by mg262** [comment]
Attaching a GeoJSON/TopoJSON file pair that demonstrate the problem, and a mapshaper visualisation of the issue:
[countries.zip](https://github.com/topojson/topojson/files/564027/countries.zip)

![topojson_incorrect_wrapping](https://cloud.githubusercontent.com/assets/8794583/19890246/5804ee64-a031-11e6-8179-f5b119e3effa.PNG)

**Comment by mbostock** [comment]
This appears to be the expected behavior of [antimeridian cutting](https://bl.ocks.org/mbostock/3788999).

Most projection systems and data sources (including standard GeoJSON; see [RFC 7946](https://tools.ietf.org/html/rfc7946#page-8)) use planar equirectangular coordinates. This means that shapefiles must be cut along the antimeridian (±180° longitude) and at the poles. It also means that the projection aspect is fixed.

D3 and TopoJSON 1.x can use either planar or spherical coordinates. When using spherical coordinates, the line between two points is interpreted as a [geodesic](https://en.wikipedia.org/wiki/Geodesic): a great circle arc representing the shortest path between the two points along the surface of the sphere. This allows a [spherical rotation](https://bl.ocks.org/mbostock/4282586) to be applied conformally before projection. The antimeridian and polar cuts (or other forms of clipping) are then re-inserted after rotation and before projection.

(This is discussed more in my FOSS4G talk, “The Toolmaker’s Guide”, but unfortunately the video is no longer available on Vimeo and I haven’t written up the talk.)

In TopoJSON 1.x, the `topojson` command-line tool “stitches” input GeoJSON, removing antimeridian and polar cuts, converting planar equirectangular coordinates into spherical coordinates. You can disable this functionality using the `--no-stitch-poles` or `--cartesian` arguments.

In TopoJSON 2.0 that is about to be released, the stitching functionality has been moved to a separate command-line tool in d3-geo-projection, [geostitch](https://github.com/d3/d3-geo-projection/blob/master/bin/geostitch), that converts planar equirectangular GeoJSON to spherical GeoJSON. This makes the conversion more explicit, and also allows you to use D3’s projection system without needing to first convert to TopoJSON.

**Comment by mg262** [comment]
`--no-stitch-poles` fixes it -- thank you.  I'm a bit puzzled, though, as the polygons in question don't encompass a pole in the source GeoJSON. Is the point that they would encompass a pole if they were stitched together?

**Comment by mbostock** [comment]
Stitching (despite the name --no-stitch-poles) applies to both poles and the antimeridian.

**Comment by mg262** [comment]
Understood.  Thank you for a very useful tool!

**Comment by mg262** [comment]
PS. may be worth updating the documentation for `--no-stitch-poles`. (I did check it before asking the q.!)

**Comment by mbostock** [comment]
I need to rewrite everything because of #291.
