### ISSUE TITLE
county borders low resolution

### ISSUE THREAD

**Issue by CristiCraciun** [topojson/topojson#332]
Hello,
I am using topojson to combine several json files after they were converted from shp with ogr2ogr. All is fine but the counties borders that appear to have a lower resolution than the original files. The files converted from shp are ok, the problem appear after using topojson. 
Do you know what can i do to preserve the details from the original files?
Thank you!

**Comment by mbostock** [comment]
Hi @CristiCraciun. This sounds like a help request and I don’t provide free support, so I recommend you try StackOverflow if you want to ask for help. When you ask for help I recommend sharing the code you are using to run topojson; otherwise, it’s difficult to speculate what could be causing the loss of resolution in your usage.

There are two things to watch out for:

1. *pre-quantization* - where you convert floating point coordinates into integer coordinates prior to computing the topology
2. *post-quantization* - where you convert floating point coordinates into integer coordinates after computing the topology
3. *simplification* - where “unimportant” points are removed

Simplification doesn’t happen automatically; it requires using topojson-simplify. But I believe topojson does do pre-quantization by default, depending on what version you’re using. You may need to adjust your quantization settings to increase the resolution, or not use quantization at all if you want a lossless conversion.

Good luck.
