### ISSUE TITLE
Enhancement request: streaming JSON parser

### ISSUE THREAD

**Issue by NelsonMinar** [topojson/topojson#80]
Currently TopoJSON parses GeoJSON with `JSON.parse()`. That in turn seems to load the whole file into memory at once, failing on giant input files. It'd be nice if TopoJSON could use a streaming JSON parser on inputs.

A quick Google search turns up several streaming JSON parsers for Node. Ie:

https://github.com/dscape/clarinet
https://github.com/creationix/jsonparse

**Comment by mbostock** [comment]
2.0 should help with this quite a bit by allowing newline-delimited JSON streams as input (see [shp2json -n](https://github.com/mbostock/shapefile/blob/master/README.md#shp2json_newline_delimited) and [ndjson-cli](https://github.com/mbostock/ndjson-cli)).

But, there remain many potential performance improvements in TopoJSON conversion, most significantly of which would be to use a single typed array for coordinates, or one typed array per dimension, rather than GeoJSON’s inherently inefficient practice of using a separate array for each point. I’m not actively working on that, so I’m closing this issue, but maybe someone else will volunteer.
